from pathlib import Path
import json
import re

root = Path(__file__).resolve().parents[1]
extensions = {'.png', '.jpg', '.jpeg', '.webp', '.gif', '.avif', '.svg', '.mp4', '.webm', '.ogv'}
galleries = {}

def natural_order(path):
    return [(0, int(part)) if part.isdigit() else (1, part.casefold())
            for part in re.split(r'(\d+)', path.as_posix())]

def media_files(paths):
    return [file.relative_to(root).as_posix() for file in sorted(paths, key=natural_order)
            if file.is_file() and not file.is_symlink() and file.suffix.lower() in extensions]

for folder in sorted((root / 'assets/projects').glob('*/gallery')):
    if folder.is_dir():
        sections = []
        loose_media = media_files(folder.iterdir())
        if loose_media:
            sections.append({'title': '', 'media': loose_media})
        for section in sorted(folder.iterdir(), key=natural_order):
            if section.is_dir() and not section.is_symlink():
                title = re.sub(r'^\d+[\s_.-]*', '', section.name).replace('_', ' ').replace('-', ' ').strip()
                title = re.sub(r'\band\b', '&', title, flags=re.IGNORECASE)
                title = re.sub(r'\bslash\b', '/', title, flags=re.IGNORECASE)
                title = title[:1].upper() + title[1:]
                sections.append({'title': title or section.name, 'media': media_files(section.rglob('*'))})
        if any(section['media'] for section in sections):
            galleries[folder.parent.relative_to(root).as_posix()] = sections

output = '// Generated by scripts/update-galleries.py from project gallery folders.\n'
output += 'const GALLERIES = ' + json.dumps(galleries, indent=2) + ';\n\n'
output += '''export function getProjectGallery(project) {
  const folder = project?.media[0]?.replace(/\\/[^/]+$/, "");
  return GALLERIES[folder];
}
'''
(root / 'src/scripts/data/galleries.js').write_text(output, encoding='utf-8')
print(f'Indexed {len(galleries)} gallery folders.')
